# Generated by Django 4.0.3 on 2022-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dusunen', '0004_categories_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slugs',
            new_name='slug',
        ),
    ]
